---
# ESP8266 Communication
esp8266:
  # Serial (old method)
  port: "/dev/ttyUSB1"
  baud: 115200
  timeout: 2.0
  use_mock: false
  
  # WiFi (new method)
  use_wifi: true
  ip: "10.163.221.143"  # ESP8266 IP matching your network

model:
  path: "../models/movenet_single_pose_lightning.tflite"
  input_size: 192   # 192x192 for lightning

camera:
  width: 640
  height: 480
  fov_deg: 60.0     # approximate FOV of your camera

control:
  base_speed: 35       # PWM% abstracted at ESP8266 side
  max_speed: 60
  angle_gain: 1.0      # scales FOV -> desired yaw
  align_deadband_deg: 4.0
  follow_target_px: 260     # target bbox height (distance proxy)
  follow_kp: 0.20
  follow_kd: 0.05

pid:
  kp: 1.2
  ki: 0.0
  kd: 0.15
  out_limit: 70

safety:
  stop_distance_cm: 30.0
  no_person_timeout_ms: 800
  
# ESP8266 Motor Controller Settings
motor_controller:
  max_speed_percent: 80
  min_speed_percent: 20
  acceleration_limit: 10  # Max speed change per step

